version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: mkdir -p  /tmp/test-results
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: if [[ -n $(gofmt -l .) ]]; then echo "Please run gofmt"; exit 1; fi
      - run: go vet -v ./...
      - run: go test -v ./cmd/ -run=VersionIsGenerated # ensure version is generated
      - run: go get golang.org/x/tools/cmd/goimports
      - run: go generate ./...
      - run: go vet -v ./...
      - run: gotestsum --junitfile  /tmp/test-results/results.xml -- ./... -short -count=1
      - run: GOARCH=386 go test ./... -short -count=1
      - store_test_results:
          path: /tmp/test-results
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"