// Copyright 2020 ConsenSys AG
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by goff (v0.3.0) DO NOT EDIT

// Package bls377 contains field arithmetic operations
package bls377

// set functions pointers to ADX version if instruction set available
func init() {
	if supportAdx {

		mulElement = _mulADXElement
		squareElement = _squareADXElement

		fromMontElement = _fromMontADXElement
	}
}

// -------------------------------------------------------------------------------------------------
// Declarations

//go:noescape
func reduceElement(res *Element)

//go:noescape
func addElement(res, x, y *Element)

//go:noescape
func _fromMontADXElement(res *Element)

//go:noescape
func _mulADXElement(res, x, y *Element)

//go:noescape
func _squareADXElement(res, x *Element)

//go:noescape
func subElement(res, x, y *Element)

// Sub  z = x - y mod q
func (z *Element) Sub(x, y *Element) *Element {
	subElement(z, x, y)
	return z
}

// SubAssign  z = z - x mod q
func (z *Element) SubAssign(x *Element) *Element {
	subElement(z, z, x)
	return z
}

// Add z = x + y mod q
func (z *Element) Add(x, y *Element) *Element {
	addElement(z, x, y)
	return z
}

// AddAssign z = z + x mod q
func (z *Element) AddAssign(x *Element) *Element {
	addElement(z, z, x)
	return z
}

// Double z = x + x mod q, aka Lsh 1
func (z *Element) Double(x *Element) *Element {
	addElement(z, x, x)
	return z
}
