on: [push, pull_request]
name: CI (develop)
jobs:
  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: gofmt
      run: if [[ -n $(gofmt -l .) ]]; then echo "please run gofmt"; exit 1; fi
    - name: go vet
      run: go vet ./...
    - name: staticcheck
      run: |
        go get -u honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...
    - name: gosec
      run: |
        go get -u github.com/securego/gosec/cmd/gosec
        gosec ./examples/...
    - name: build
      run: go build
    - name: check version
      run: goffVersion=$(./goff --version | cut -d ' ' -f 3-);gitVersion=$(git describe --abbrev=0);if [[ $goffVersion != $gitVersion ]]; then echo "goff version doesn't match git last semver tag"; exit 1; fi;
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - staticcheck
    steps:
    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go mod download
      run: go mod download
    - name: install deps
      if: github.ref == 'refs/heads/master'
      run: go get golang.org/x/tools/cmd/goimports && go get github.com/klauspost/asmfmt/cmd/asmfmt
    - name: Test (master)
      if: github.ref == 'refs/heads/master'
      run: |
        go test -v -short ./...
        go test -v -race -short ./...
        go test -v -tags=noadx -short ./...
    - name: Test (!master)
      if: github.ref != 'refs/heads/master'
      run: |
        go test -v -short ./examples/...
        go test -v -race -short ./examples/...
        go test -v -tags=noadx -short ./examples/...
    - name: Test (32bits -- GOARCH=386)
      if: matrix.os == 'ubuntu-latest'
      run: GOARCH=386 go test -v -short ./examples/...

  slack-workflow-status:
    if: always()
    name: post workflow status to slack
    needs:
      - staticcheck
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          channel: '#team-gnark'
          include_jobs: false