on: [push, pull_request]
name: goff CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: install bin dependencies
      run: go get golang.org/x/tools/cmd/goimports && go get github.com/klauspost/asmfmt/cmd/asmfmt
    - name: generate files
      run: go generate ./...
    - name: gofmt
      run: if [[ -n $(gofmt -l .) ]]; then echo "Please run gofmt"; exit 1; fi
    - name: go vet
      run: go vet ./...
    - name: staticcheck
      run: |
        go get -u honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...
    - name: gosec
      run: |
        go get -u github.com/securego/gosec/cmd/gosec
        gosec ./examples/...
    - name: build
      run: go build
    - name: check version
      run: goffVersion=$(./goff --version | cut -d ' ' -f 3-);gitVersion=$(git describe --abbrev=0);if [[ $goffVersion != $gitVersion ]]; then echo "goff version doesn't match git last semver tag"; exit 1; fi;
    - name: Test
      run: |
        go test -short ./...
        go test -race -short ./...
    - name: Test (tags = noadx)
      run: go test -tags=noadx -short ./...
    - name: Test (32bits -- GOARCH=386)
      if: matrix.os == 'ubuntu-latest'
      run: |
        GOARCH=386 go test -short ./examples/...

  slack-workflow-status:
    if: always()
    name: post workflow status to slack
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#team-gnark'
          name: 'goff CI'